development:
  adapter: postgresql
  database: users
  host:localhost
  username: jasdeep1
  password:

test:
  adapter: postgresql
  database: users
  host: localhost
  username: jasdeep1
  password:

production:
  adapter: postgresql
  database: users
  username: 
  password: